version: "3"

services: 

    docker-mysql:
        restart: always
        container_name: docker-mysql
        image: mysql
        environment:
            MYSQL_DATABASE: incident
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - "6033:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10    

    #backend:
    #    container_name: backend
    #    build:
    #        context: ./
    #        dockerfile: Dockerfile
        #restart: always
        #dolinks:
        #  - mongo
        #volumes:
        #- /data/incident
     #   environment:
     #       WAIT_HOSTS: mysql:3306
     #   ports:
     #   - "8888:8080"